export const SET_MONSTER_ID = "SET_MONSTER_ID";
export const SET_MONSTER_KILLED = "SET_MONSTER_KILLED";

export const MONSTERS = [
  {
    monsterName: "Gremlin",
    monsterHealth: 65,
    monsterExperience: 30,
    monsterSpellPoint: 1,
    monsterLevel: 1,
    monsterDamage: 7,
    monsterPhysicalDefence: 40,
    monsterDrop: [{ id: "id_0", count: 3 }],
    isPassed: true,
    monsterImage: require("../assets/gremlin.png"),
  },
  {
    monsterName: "Bearded Keltir",
    monsterHealth: 95,
    monsterExperience: 45,
    monsterSpellPoint: 2,
    monsterLevel: 2,
    monsterDamage: 8,
    monsterPhysicalDefence: 42,
    monsterDrop: [
      { id: "id_0", count: 6 },
      { id: "id_1", count: 1 },
      { id: "id_2", count: 1 },
      { id: "id_3", count: 1 },
    ],
    isPassed: true,
    monsterImage: require("../assets/Dog.png"),
  },
  {
    monsterName: "Goblin",
    monsterHealth: 105,
    monsterExperience: 133,
    monsterSpellPoint: 4,
    monsterLevel: 3,
    monsterDamage: 9,
    monsterPhysicalDefence: 58,
    monsterDrop: [
      { id: "id_0", count: 8 },
      { id: "id_2", count: 1 },
      { id: "id_6", count: 1 },
      { id: "id_1", count: 1 },
    ],
    isPassed: false,
    monsterImage: require("../assets/Goblin.png"),
  },
  {
    monsterName: "Orc Warrior",
    monsterHealth: 112,
    monsterExperience: 177,
    monsterSpellPoint: 6,
    monsterLevel: 4,
    monsterDamage: 10,
    monsterPhysicalDefence: 68,
    monsterDrop: [
      { id: "id_0", count: 10 },
      { id: "id_2", count: 1 },
      { id: "id_6", count: 1 },
      { id: "id_1", count: 1 },
    ],
    isPassed: false,
    monsterImage: require("../assets/Orc.png"),
  },
  {
    monsterName: "Gray Wolf",
    monsterHealth: 308,
    monsterExperience: 221,
    monsterSpellPoint: 7,
    monsterLevel: 5,
    monsterDamage: 12,
    monsterPhysicalDefence: 80,
    monsterDrop: [
      { id: "id_0", count: 12 },
      { id: "id_2", count: 1 },
      { id: "id_1", count: 1 },
    ],
    isPassed: false,
    monsterImage: require("../assets/GrayWolf.png"),
  },

  {
    monsterName: "BOSS: Evil Snake",
    monsterHealth: 3146,
    monsterExperience: 1005,
    monsterSpellPoint: 35,
    monsterLevel: 5,
    monsterDamage: 36,
    monsterPhysicalDefence: 126,
    monsterDrop: [
      { id: "id_0", count: 60 },
      { id: "id_2", count: 3 },
      { id: "id_1", count: 3 },
    ],
    isPassed: false,
    monsterImage: require("../assets/BossEvilSnake.png"),
  },

  {
    monsterName: "Eye",
    monsterHealth: 155,
    monsterExperience: 265,
    monsterSpellPoint: 8,
    monsterLevel: 6,
    monsterDamage: 13,
    monsterPhysicalDefence: 93,
    monsterDrop: [
      { id: "id_0", count: 22 },
      { id: "id_2", count: 1 },
      { id: "id_6", count: 1 },
      { id: "id_1", count: 1 },
    ],
    isPassed: false,
    monsterImage: require("../assets/Eye.png"),
  },
  {
    monsterName: "Tunath Orc Marksman",
    monsterHealth: 180,
    monsterExperience: 309,
    monsterSpellPoint: 10,
    monsterLevel: 7,
    monsterDamage: 14,
    monsterPhysicalDefence: 108,
    monsterDrop: [
      { id: "id_0", count: 28 },
      { id: "id_2", count: 1 },
      { id: "id_6", count: 1 },
      { id: "id_1", count: 1 },
    ],
    isPassed: false,
    monsterImage: require("../assets/TunathOrcMarksman.png"),
  },
  {
    monsterName: "Giant Toad",
    monsterHealth: 207,
    monsterExperience: 354,
    monsterSpellPoint: 11,
    monsterLevel: 8,
    monsterDamage: 16,
    monsterPhysicalDefence: 126,
    monsterDrop: [
      { id: "id_0", count: 33 },
      { id: "id_2", count: 1 },
      { id: "id_6", count: 1 },
      { id: "id_1", count: 1 },
    ],
    isPassed: false,
    monsterImage: require("../assets/GiantToad.png"),
  },
  {
    monsterName: "Vaiss Orc",
    monsterHealth: 350,
    monsterExperience: 353,
    monsterSpellPoint: 11,
    monsterLevel: 9,
    monsterDamage: 18,
    monsterPhysicalDefence: 143,
    monsterDrop: [
      { id: "id_0", count: 38 },
      { id: "id_2", count: 1 },
      { id: "id_6", count: 1 },
      { id: "id_1", count: 1 },
    ],
    isPassed: false,
    monsterImage: require("../assets/VaissOrc.png"),
  },
];
