export const SET_CHARACTER_LEVEL = "SET_CHARACTER_LEVEL";
export const PICK_UP_DROPPED_ITEM = "PICK_UP_DROPPED_ITEM";
export const CHARACTER_RECEIVE_DAMAGE = "CHARACTER_RECEIVE_DAMAGE";
export const CHARACTER_RESSURECTION = "CHARACTER_RESSURECTION";
export const CHARACTER_HEALTH_REGENERATION = "CHARACTER_HEALTH_REGENERATION";
export const CHARACTER_MANA_REGENERATION = "CHARACTER_MANA_REGENERATION";
export const EQUIP_ITEM = "EQUIP_ITEM";

export const SKILLS = [
  {
    skillName: "Power Strike",
    skillDamage: 65,
    skillPrice: 30,
  },
];

export const LEVELS_UP_EXPERIENCE = {
  level_1: 68,
  level_2: 296,
  level_3: 805,
  level_4: 1716,
  level_5: 3154,
  level_6: 5249,
  level_7: 8136,
  level_8: 11955,
  level_9: 16851,
  level_10: 22973,
  level_11: 30475,
  level_12: 39516,
  level_13: 50261,
  level_14: 62876,
  level_15: 77537,
  level_16: 94421,
  level_17: 113712,
  level_18: 135596,
  level_19: 160267,
  level_20: 187921,
  level_21: 415430,
  level_22: 509282,
  level_23: 620353,
  level_24: 751775,
  level_25: 906547,
  level_26: 1087989,
  level_27: 1087989,
  level_28: 1087989,
  level_29: 1087989,
  level_30: 1087989,
  level_31: 1087989,
  level_32: 1087989,
  level_33: 1087989,
  level_34: 1087989,
  level_35: 1087989,
  level_36: 1087989,
  level_37: 1087989,
  level_38: 1087989,
  level_39: 1087989,
  level_40: 1087989,
};

export const ITEMS_LIST = {
  id_0: {
    itemName: "Adena",
    itemUsage: "Main currency",
    isStackable: true,
    itemImage: require("../../../../assets/drop/adena.png"),
  },
  id_1: {
    itemName: "Charcoal",
    itemUsage: "Used for craft",
    isStackable: true,
    itemImage: require("../../../../assets/drop/charcoal.png"),
  },
  id_2: {
    itemName: "Thread",
    itemUsage: "Used for craft",
    isStackable: true,
    itemImage: require("../../../../assets/drop/Thread.png"),
  },

  id_3: {
    itemName: "Adamantite",
    itemUsage: "Used for craft",
    isStackable: true,
    itemImage: require("../../../../assets/drop/adamantite.png"),
  },
  id_4: {
    itemName: "Braided Hemp",
    itemUsage: "Used for craft",
    isStackable: true,
    itemImage: require("../../../../assets/drop/braided.png"),
  },
  id_5: {
    itemName: "Coal",
    itemUsage: "Used for craft",
    isStackable: true,
    itemImage: require("../../../../assets/drop/coal.png"),
  },
  id_6: {
    itemName: "Animal Skin",
    isStackable: true,
    itemImage: require("../../../../assets/drop/Skin.png"),
  },
  id_7: {
    itemName: "Animal Skin",
    isStackable: true,
    itemImage: require("../../../../assets/drop/soulShotD.png"),
  },
  id_99: {
    itemName: "Gold Coin",
    itemUsage: "Donate currency",
    isStackable: true,
    itemImage: require("../../../../assets/drop/gold.png"),
  },
};

export const EQUIPMENT_LIST = {
  WEAPON: {
    id_0: {
      itemName: "Handmade Sword",
      itemGrade: 1,
      physicalDamage: 17,
      magicalDamage: 12,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Wepons/HandmadeSword.jpg"),
    },
    id_1: {
      itemName: "Elven Sword",
      itemGrade: 20,
      physicalDamage: 51,
      magicalDamage: 23,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Wepons/ElvenSword.jpg"),
    },
    id_2: {
      itemName: "Katana",
      itemGrade: 40,
      physicalDamage: 122,
      magicalDamage: 68,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Wepons/Katana.jpg"),
    },
  },
  EARRING: {
    id_0: {
      itemName: "Coral Earring",
      itemGrade: 1,
      physicalDefence: 0,
      magicalDefence: 21,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Earrings/CoralEarring.jpg"),
    },
    id_1: {
      itemName: "	Elven Earring",
      itemGrade: 20,
      physicalDefence: 0,
      magicalDefence: 34,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Earrings/ElvenEarring.jpg"),
    },
    id_2: {
      itemName: "Nassen's Earring",
      itemGrade: 40,
      physicalDefence: 0,
      magicalDefence: 48,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Earrings/NassenEarring.jpg"),
    },
  },
  HELMET: {
    id_0: {
      itemName: "Leather Helmet",
      itemGrade: 1,
      physicalDefence: 23,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Helmets/LeatherHelmet.jpg"),
    },
    id_1: {
      itemName: "Brigandine Helmet",
      itemGrade: 20,
      physicalDefence: 41,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Helmets/BrigandineHelmet.jpg"),
    },
    id_2: {
      itemName: "Plate Helmet",
      itemGrade: 40,
      physicalDefence: 0,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Helmets/PlateHelmet.jpg"),
    },
  },
  NECKLACE: {
    id_0: {
      itemName: "Blue Diamond Necklace",
      itemGrade: 1,
      physicalDefence: 0,
      magicalDefence: 28,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Necklace/BlueDiamondNecklace.jpg"),
    },
    id_1: {
      itemName: "	Elven Necklace",
      itemGrade: 20,
      physicalDefence: 0,
      magicalDefence: 45,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Necklace/ElvenNecklace.jpg"),
    },
    id_2: {
      itemName: "Necklace of Mermaid",
      itemGrade: 40,
      physicalDefence: 0,
      magicalDefence: 60,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Necklace/NecklaceofMermaid.jpg"),
    },
  },
  ARMOR: {
    id_0: {
      itemName: "Bronze Breastplate",
      itemGrade: 1,
      physicalDefence: 68,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Armors/BronzeBreastplate.jpg"),
    },
    id_1: {
      itemName: "Brigandine",
      itemGrade: 20,
      physicalDefence: 74,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Armors/Brigandine.jpg"),
    },
    id_2: {
      itemName: "Full Plate Armor",
      itemGrade: 40,
      physicalDefence: 86,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Armors/FullPlateArmor.jpg"),
    },
  },
  SHIELD: {
    id_0: {
      itemName: "Buckler",
      itemGrade: 1,
      physicalDefence: 68,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Shields/Buckler.jpg"),
    },
    id_1: {
      itemName: "Brigandine Shield",
      itemGrade: 20,
      physicalDefence: 100,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Shields/BrigandineShield.jpg"),
    },
    id_2: {
      itemName: "Full Plate Shield",
      itemGrade: 40,
      physicalDefence: 203,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Shields/FullPlateShield.jpg"),
    },
  },
  GLOVES: {
    id_0: {
      itemName: "Leather Gloves",
      itemGrade: 1,
      physicalDefence: 15,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Gloves/LeatherGloves.jpg"),
    },
    id_1: {
      itemName: "Brigandine Gauntlets",
      itemGrade: 20,
      physicalDefence: 22,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Gloves/BrigandineGauntlets.jpg"),
    },
    id_2: {
      itemName: "Full Plate Gauntlets",
      itemGrade: 40,
      physicalDefence: 39,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Gloves/FullPlateGauntlets.jpg"),
    },
  },
  PANTS: {
    id_0: {
      itemName: "Bronze Gaiters",
      itemGrade: 1,
      physicalDefence: 43,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Pants/BronzeGaiters.jpg"),
    },
    id_1: {
      itemName: "Brigandine Gaiters",
      itemGrade: 20,
      physicalDefence: 64,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Pants/BrigandineGaiters.jpg"),
    },
    id_2: {
      itemName: "Full Plate Pants",
      itemGrade: 40,
      physicalDefence: 75,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Pants/FullPlatePants.jpg"),
    },
  },
  BOOTS: {
    id_0: {
      itemName: "Leather Shoes",
      itemGrade: 1,
      physicalDefence: 13,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Boots/LeatherShoes.jpg"),
    },
    id_1: {
      itemName: "Brigandine Boots",
      itemGrade: 20,
      physicalDefence: 27,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Boots/BrigandineBoots.jpg"),
    },
    id_2: {
      itemName: "Full Plate Boots",
      itemGrade: 40,
      physicalDefence: 39,
      magicalDefence: 0,
      isStackable: false,
      itemImage: require("../../../../assets/Equipment/Boots/FullPlateBoots.jpg"),
    },
  },
};
